# Generated by Django 4.1 on 2022-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_story_delete_blogpost_comments_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='time',
        ),
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
