# Generated by Django 4.1 on 2022-09-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_story_time_story_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='storyType',
            new_name='type',
        ),
    ]
